version: "3.8"



services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    build: ../het
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env