# Generated by Django 4.2.5 on 2023-09-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название.', max_length=200, verbose_name='Название.')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItemModel',
            fields=[
                ('itemmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.itemmodel')),
                ('currency', models.CharField(choices=[('RUB', 'RUB')], default='RUB', max_length=5, verbose_name='Валюта')),
                ('sum_of_expense', models.PositiveIntegerField(verbose_name='Сумма')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время занесения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            bases=('core.itemmodel',),
        ),
    ]
