# Generated by Django 4.2.5 on 2023-09-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'RUB')], default='RUB', max_length=5, verbose_name='Валюта')),
                ('sum_of_expense', models.PositiveIntegerField(verbose_name='Сумма')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время занесения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название категории расхода', max_length=200, verbose_name='Название категории расхода')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категори расхода',
            },
        ),
    ]
