# Generated by Django 4.2.5 on 2023-10-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_transactionitemmodel_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transactionitemmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transactionitemmodel')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
            bases=('core.transactionitemmodel',),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('itemmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.itemmodel')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категори расходов',
            },
            bases=('core.itemmodel',),
        ),
    ]
