# Generated by Django 4.2.5 on 2023-09-10 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'name')},
        ),
    ]
